import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { getFirestore, addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=id=>document.getElementById(id),val=id=>($(id)?.value||"").trim(),setVal=(id,v="")=>{if($(id))$(id).value=v};
async function list(c){let s=await getDocs(collection(db,c));return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
function bind(id,fn){$(id)?.addEventListener("click",async e=>{e.preventDefault();try{await fn()}catch(err){alert("오류: "+err.message);console.error(err)}})}
function item(t,b,a){return`<article class="item"><h3>${t}</h3><p>${b||""}</p><div class="actions">${a||""}</div></article>`}function money(v){return Number(String(v||"").replace(/[^\d]/g,""))||0}function safe(s){return String(s||"").replaceAll("'","\\'").replaceAll("\n"," ")}
async function upload(fs,folder){let u=[];for(let f of Array.from(fs||[])){let r=ref(storage,`${folder}/${Date.now()}_${f.name}`);await uploadBytes(r,f);u.push(await getDownloadURL(r))}return u}
bind("adminLogin",()=>signInWithEmailAndPassword(auth,val("adminEmail"),val("adminPw")));bind("adminLogout",()=>signOut(auth));onAuthStateChanged(auth,u=>{$("loginBox").classList.toggle("hide",!!u);$("adminPanel").classList.toggle("hide",!u);if(u){loadSettings();loadAll();startAdminRealtime()}});

let adminRealtimeStarted=false;
function startAdminRealtime(){
  if(adminRealtimeStarted) return;
  adminRealtimeStarted=true;
  ["orders","bookings","members","coupons","products","consultPrices","notices","posts","reviews","settings"].forEach(col=>{
    try{onSnapshot(collection(db,col),()=>{loadSettings();loadAll();});}catch(e){console.warn("admin sync",col,e)}
  });
}

async function loadSettings(){let s=await list("settings"),p=s.find(x=>x.id=="payment")||{},b=s.find(x=>x.id=="business")||{},t=s.find(x=>x.id=="bookingTimes")||{};["payName","payAccount","payLink","bankName","bankOwner","bankAccount","payGuide"].forEach(id=>setVal(id,p[id.replace("pay","").toLowerCase()]||p[id]||""));setVal("payName",p.name||"");setVal("payAccount",p.account||"");["bizNameAdmin","bizOwnerAdmin","bizNumberAdmin","bizAddressAdmin","bizTypeAdmin","bizItemAdmin","bizContactAdmin","bizMailOrderAdmin"].forEach(id=>{});setVal("bizNameAdmin",b.name||"천율도령");setVal("bizOwnerAdmin",b.owner||"정세진");setVal("bizNumberAdmin",b.number||"570-76-00713");setVal("bizAddressAdmin",b.address||"경상북도 구미시 상모로12길 49, 101동 102호");setVal("bizTypeAdmin",b.type||"협회 및 단체, 수리 및 기타 개인서비스업");setVal("bizItemAdmin",b.item||"점술 및 유사 서비스업");setVal("bizContactAdmin",b.contact||"카카오톡 오픈프로필 '천율도령'");setVal("bizMailOrderAdmin",b.mailOrder||"신고 예정");setVal("timeInput",(t.times||[]).join("\n"));setVal("blockInput",(t.blockedDates||[]).join("\n"))}
bind("saveBiz",()=>setDoc(doc(db,"settings","business"),{footerName:"천율도령 공식 신점 상담",name:val("bizNameAdmin"),owner:val("bizOwnerAdmin"),number:val("bizNumberAdmin"),address:val("bizAddressAdmin"),type:val("bizTypeAdmin"),item:val("bizItemAdmin"),contact:val("bizContactAdmin"),mailOrder:val("bizMailOrderAdmin"),updatedAt:serverTimestamp()},{merge:true}).then(()=>alert("저장 완료")));
bind("savePay",async()=>{let imgs=await upload($("payQr").files,"payment");let data={name:val("payName"),account:val("payAccount"),link:val("payLink"),bankName:val("bankName"),bankOwner:val("bankOwner"),bankAccount:val("bankAccount"),guide:val("payGuide"),updatedAt:serverTimestamp()};if(imgs[0])data.qr=imgs[0];await setDoc(doc(db,"settings","payment"),data,{merge:true});alert("저장 완료")});
bind("saveTime",()=>setDoc(doc(db,"settings","bookingTimes"),{times:val("timeInput").split("\n").map(x=>x.trim()).filter(Boolean),blockedDates:val("blockInput").split("\n").map(x=>x.trim()).filter(Boolean),updatedAt:serverTimestamp()},{merge:true}).then(()=>alert("저장 완료")));
bind("savePrice",async()=>{let d={title:val("priceTitle"),price:val("priceAmount"),badge:val("priceBadge"),desc:val("priceDesc"),createdAt:serverTimestamp()};val("priceId")?await updateDoc(doc(db,"consultPrices",val("priceId")),d):await addDoc(collection(db,"consultPrices"),d);loadAll()});
bind("addProduct",async()=>{let imgs=await upload($("pImages").files,"products");await addDoc(collection(db,"products"),{name:val("pName"),category:val("pCategory"),price:val("pPrice"),sale:val("pSale"),stock:val("pStock"),desc:val("pDesc"),images:imgs,createdAt:serverTimestamp()});loadAll()});
function code(prefix="CHEON"){let chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",c=prefix+"-";for(let i=0;i<6;i++)c+=chars[Math.floor(Math.random()*chars.length)];return c}
bind("addCoupon",async()=>{await addDoc(collection(db,"coupons"),{code:val("couponCode").toUpperCase(),discount:val("couponDiscount"),desc:val("couponDesc"),used:false,auto:false,createdAt:serverTimestamp()});loadAll()});
bind("autoCoupon",async()=>{let n=Math.min(100,Math.max(1,parseInt(val("couponCount")||"1"))),made=[];for(let i=0;i<n;i++){let c=code(val("couponPrefix")||"CHEON");made.push(c);await addDoc(collection(db,"coupons"),{code:c,discount:val("couponDiscount"),desc:val("couponDesc")||"자동 쿠폰",used:false,auto:true,createdAt:serverTimestamp()})}alert(`${n}개 발급 완료`);loadAll()});
bind("issueMemberCoupon",async()=>{let sel=$("memberSelect"),uid=sel.value;if(!uid)return alert("회원 선택");let opt=sel.options[sel.selectedIndex];let c=(val("mCouponCode")||code("MEMBER")).toUpperCase();await addDoc(collection(db,"coupons"),{code:c,discount:val("mCouponDiscount"),desc:val("mCouponDesc")||"회원 전용 쿠폰",used:false,memberUid:uid,memberEmail:opt.dataset.email,memberName:opt.dataset.name,createdAt:serverTimestamp()});alert("발급 완료");loadAll()});
bind("addNotice",()=>addDoc(collection(db,"notices"),{tag:val("noticeTag"),title:val("noticeTitle"),body:val("noticeBody"),createdAt:serverTimestamp()}).then(loadAll));
bind("addPost",async()=>{let imgs=await upload($("postImages").files,"posts");await addDoc(collection(db,"posts"),{title:val("postTitle"),body:val("postBody"),images:imgs,createdAt:serverTimestamp()});loadAll()});
let adminLoading=false;
async function loadAll(){if(adminLoading)return; adminLoading=true; try{let [orders,bookings,members,coupons,products,prices,notices,posts,reviews]=await Promise.all(["orders","bookings","members","coupons","products","consultPrices","notices","posts","reviews"].map(list));$("statOrders").textContent=orders.length;$("statBookings").textContent=bookings.length;$("statMembers").textContent=members.length;$("statSales").textContent=orders.reduce((s,o)=>s+money(o.total),0).toLocaleString()+"원";$("memberSelect").innerHTML='<option value="">회원 선택</option>'+members.map(m=>`<option value="${m.id}" data-email="${m.email||""}" data-name="${m.name||""}">${m.name||"이름 없음"} / ${m.email||""}</option>`).join("");$("memberList").innerHTML=members.map(m=>item(`${m.name||"이름 없음"} · ${m.email||""}`,`연락처: ${m.contact||""}`,`<button class="danger" onclick="del('members','${m.id}')">삭제</button>`)).join("")||"<p>회원 없음</p>";$("couponList").innerHTML=coupons.filter(c=>!c.memberUid&&!c.memberEmail).map(c=>item(`${c.code} · ${c.discount}원`,`${c.desc||""}<br>${c.used?"사용완료":"사용가능"}`,`<button class="danger" onclick="del('coupons','${c.id}')">삭제</button>`)).join("");$("memberCouponList").innerHTML=coupons.filter(c=>c.memberUid||c.memberEmail).map(c=>item(`${c.code} · ${c.discount}원`,`${c.memberName||c.memberEmail}<br>${c.used?"사용완료":"사용가능"}`,`<button class="danger" onclick="del('coupons','${c.id}')">삭제</button>`)).join("");$("priceAdminList").innerHTML=prices.map(p=>item(`${p.title} · ${p.price}`,p.desc,`<button onclick="editPrice('${p.id}','${safe(p.title)}','${safe(p.price)}','${safe(p.badge)}','${safe(p.desc)}')">수정</button><button class="danger" onclick="del('consultPrices','${p.id}')">삭제</button>`)).join("");$("productAdminList").innerHTML=products.map(p=>item(`${p.name} · ${p.price}`,`${p.category||""}<br>${p.stock||""}`,`<button class="danger" onclick="del('products','${p.id}')">삭제</button>`)).join("");$("cancelList").innerHTML=[
  ...orders.filter(o=>String(o.status||"").includes("취소")).map(o=>item(`상품 주문 취소 · ${o.orderNo||o.id}`,`주문자:${o.name||""}<br>금액:${o.total||""}<br>사유:${o.cancelReason||"-"}<br>상태:${o.status}`,`<button onclick="status('orders','${o.id}','취소완료')">취소완료</button><button onclick="status('orders','${o.id}','취소반려')">반려</button>`)),
  ...bookings.filter(b=>String(b.status||"").includes("취소")).map(b=>item(`상담 예약 취소 · ${b.name||""}`,`${b.date||""} ${b.time||""}<br>사유:${b.cancelReason||"-"}<br>상태:${b.status}`,`<button onclick="status('bookings','${b.id}','취소완료')">취소완료</button><button onclick="status('bookings','${b.id}','취소반려')">반려</button>`))
].join("")||"<p>취소 요청이 없습니다.</p>";
$("orderList").innerHTML=orders.map(o=>item(`${o.orderNo} · ${o.name} · ${o.total}`,`연락처:${o.contact}<br>상태:${o.status}<br>쿠폰:${o.coupon||"-"}<br>배송:${o.trackingCompany||"-"} ${o.trackingNo||""}`,`<button onclick="status('orders','${o.id}','입금완료')">입금완료</button><button onclick="status('orders','${o.id}','취소완료')">취소</button><button onclick="tracking('${o.id}')">배송입력</button><button class="danger" onclick="del('orders','${o.id}')">삭제</button>`)).join("");$("bookingList").innerHTML=bookings.map(b=>item(`${b.name} · ${b.type}`,`${b.contact}<br>${b.date} ${b.time}<br>${b.body}`,`<button onclick="status('bookings','${b.id}','확정')">확정</button><button onclick="status('bookings','${b.id}','취소완료')">취소</button><button class="danger" onclick="del('bookings','${b.id}')">삭제</button>`)).join("");$("noticeAdminList").innerHTML=notices.map(n=>item(n.title,n.body,`<button class="danger" onclick="del('notices','${n.id}')">삭제</button>`)).join("");$("postAdminList").innerHTML=posts.map(p=>item(p.title,p.body,`<button class="danger" onclick="del('posts','${p.id}')">삭제</button>`)).join("");let pend=reviews.filter(r=>!r.approved),appv=reviews.filter(r=>r.approved);$("pendingReviews").innerHTML=pend.map(r=>item(r.name,r.body,`<button onclick="approve('${r.id}',true)">승인</button><button class="danger" onclick="del('reviews','${r.id}')">삭제</button>`)).join("");$("approvedReviews").innerHTML=appv.map(r=>item(r.name,r.body,`<button onclick="approve('${r.id}',false)">승인취소</button><button class="danger" onclick="del('reviews','${r.id}')">삭제</button>`)).join("")}finally{adminLoading=false}}
window.editPrice=(id,t,p,b,d)=>{setVal("priceId",id);setVal("priceTitle",t);setVal("priceAmount",p);setVal("priceBadge",b);setVal("priceDesc",d);location.hash="#prices"};window.del=async(c,id)=>{if(confirm("삭제?")){await deleteDoc(doc(db,c,id));loadAll()}};window.status=async(c,id,s)=>{await updateDoc(doc(db,c,id),{status:s});loadAll()};window.tracking=async(id)=>{let trackingCompany=prompt("택배사/배송방법"),trackingNo=prompt("송장번호/메모");await updateDoc(doc(db,"orders",id),{trackingCompany,trackingNo,status:"배송중"});loadAll()};window.approve=async(id,a)=>{await updateDoc(doc(db,"reviews",id),{approved:a});loadAll()};