import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, setDoc, updateDoc, deleteDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=id=>document.getElementById(id),val=id=>($(id)?.value||"").trim(),money=v=>Number(String(v||"").replace(/[^\d]/g,""))||0;
async function list(c){let s=await getDocs(collection(db,c));return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
async function upload(fs,folder){let u=[];for(let f of Array.from(fs||[])){let r=ref(storage,`${folder}/${Date.now()}_${f.name}`);await uploadBytes(r,f);u.push(await getDownloadURL(r))}return u}
function code(){return"CY-"+Math.random().toString(36).slice(2,8).toUpperCase()}function card(t,b,a=""){return`<div class="card"><h3>${t}</h3><p>${b||""}</p>${a}</div>`}
function goTab(id){document.querySelectorAll(".adminTab").forEach(x=>x.classList.add("hide"));$(id).classList.remove("hide")}
async function load(){let [orders,bookings,members,coupons,products,prices,settings]=await Promise.all(["orders","bookings","members","coupons","products","consultPrices","settings"].map(list));$("statOrders").textContent=orders.length;$("statBookings").textContent=bookings.length;$("statMembers").textContent=members.length;$("statSales").textContent=orders.reduce((s,o)=>s+money(o.total),0).toLocaleString()+"원";$("memberSelect").innerHTML=`<option value="">공용 쿠폰</option>`+members.map(m=>`<option value="${m.id}" data-email="${m.email||""}" data-name="${m.name||""}">${m.name||"이름 없음"} / ${m.email||""}</option>`).join("");$("orderList").innerHTML=orders.map(o=>card(o.orderNo||o.id,`${o.name||""}<br>${o.total||""}<br>${o.status||""}`,`<button class="secondary" onclick="st('orders','${o.id}','입금완료')">입금완료</button><button class="secondary" onclick="tr('${o.id}')">배송입력</button><button class="secondary" onclick="st('orders','${o.id}','취소완료')">취소</button>`)).join("");$("bookingList").innerHTML=bookings.map(b=>card(b.name||"",`${b.type||""}<br>${b.date||""} ${b.time||""}<br>${b.status||""}`,`<button class="secondary" onclick="st('bookings','${b.id}','확정')">확정</button><button class="secondary" onclick="st('bookings','${b.id}','취소완료')">취소</button>`)).join("");$("memberList").innerHTML=members.map(m=>card(m.name||"회원",`${m.email||""}<br>${m.contact||""}`)).join("");$("couponList").innerHTML=coupons.map(c=>card(c.code,`${c.discount}원<br>${c.memberName||"공용"}<br>${c.used?"사용완료":"사용가능"}`)).join("");$("productListAdmin").innerHTML=products.map(p=>card(p.name,`${p.price}<br>${p.stock||""}`,`<button class="secondary" onclick="del('products','${p.id}')">삭제</button>`)).join("");$("priceListAdmin").innerHTML=prices.map(p=>card(p.title,`${p.price}<br>${p.desc||""}`,`<button class="secondary" onclick="del('consultPrices','${p.id}')">삭제</button>`)).join("");let pay=settings.find(s=>s.id=="payment")||{},time=settings.find(s=>s.id=="bookingTimes")||{};$("payAccount").value=pay.account||"";$("payLink").value=pay.link||"";$("bankName").value=pay.bankName||"";$("bankOwner").value=pay.bankOwner||"";$("bankAccount").value=pay.bankAccount||"";$("payGuide").value=pay.guide||"";$("timeInput").value=(time.times||[]).join("\n");$("blockInput").value=(time.blockedDates||[]).join("\n")}
async function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>goTab(b.dataset.tab));$("adminLogin").onclick=()=>signInWithEmailAndPassword(auth,val("adminEmail"),val("adminPw")).catch(e=>alert("로그인 실패"));$("adminLogout").onclick=()=>signOut(auth);$("addCoupon").onclick=async()=>{let sel=$("memberSelect"),uid=sel.value,opt=sel.options[sel.selectedIndex];await addDoc(collection(db,"coupons"),{code:(val("couponCode")||code()).toUpperCase(),discount:val("couponDiscount"),desc:val("couponDesc"),used:false,memberUid:uid||"",memberEmail:opt?.dataset.email||"",memberName:opt?.dataset.name||"",createdAt:serverTimestamp()});load()};$("addProduct").onclick=async()=>{let imgs=await upload($("pImages").files,"products");await addDoc(collection(db,"products"),{name:val("pName"),price:val("pPrice"),stock:val("pStock"),desc:val("pDesc"),images:imgs,createdAt:serverTimestamp()});load()};$("addPrice").onclick=async()=>{await addDoc(collection(db,"consultPrices"),{title:val("priceTitle"),price:val("priceAmount"),desc:val("priceDesc"),createdAt:serverTimestamp()});load()};$("savePay").onclick=()=>setDoc(doc(db,"settings","payment"),{account:val("payAccount"),link:val("payLink"),bankName:val("bankName"),bankOwner:val("bankOwner"),bankAccount:val("bankAccount"),guide:val("payGuide"),updatedAt:serverTimestamp()},{merge:true}).then(()=>alert("저장 완료"));$("saveBooking").onclick=()=>setDoc(doc(db,"settings","bookingTimes"),{times:val("timeInput").split("\n").map(x=>x.trim()).filter(Boolean),blockedDates:val("blockInput").split("\n").map(x=>x.trim()).filter(Boolean),updatedAt:serverTimestamp()},{merge:true}).then(()=>alert("저장 완료"))}
window.st=async(c,id,s)=>{await updateDoc(doc(db,c,id),{status:s,updatedAt:serverTimestamp()});load()};window.tr=async(id)=>{let trackingCompany=prompt("택배사"),trackingNo=prompt("송장번호");await updateDoc(doc(db,"orders",id),{trackingCompany,trackingNo,status:"배송중"});load()};window.del=async(c,id)=>{if(confirm("삭제?")){await deleteDoc(doc(db,c,id));load()}};
onAuthStateChanged(auth,u=>{$("adminLoginBox").classList.toggle("hide",!!u);$("adminPanel").classList.toggle("hide",!u);if(u)load()});["orders","bookings","members","coupons","products","consultPrices","settings"].forEach(c=>onSnapshot(collection(db,c),()=>{if(!$("adminPanel").classList.contains("hide"))load()}));bind();