import{initializeApp}from"https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";import{getFirestore,collection,addDoc,getDocs,query,orderBy,where,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js";const app=initializeApp(firebaseConfig),db=getFirestore(app);let selectedProduct=null;
const defaults={fields:[{title:"연애 · 재회",body:"상대방 속마음, 연락운, 재회 흐름을 살펴봅니다."},{title:"금전운 · 사업운",body:"매출, 계약, 선택의 방향을 함께 봅니다."}],products:[{name:"평안 염주",price:"25,000원",stock:"주문 가능",desc:"마음의 평안과 좋은 흐름을 담은 염주입니다."}],notices:[{tag:"필독",title:"상담 안내",body:"상담은 예약제로 진행됩니다."}],reviews:[{name:"김OO님",category:"재회 상담",stars:"★★★★★",body:"흐름을 정리하는 데 도움이 되었습니다."}]};
async function load(col,id,html,def=[]){const box=document.getElementById(id);try{const s=await getDocs(query(collection(db,col),orderBy("createdAt","desc")));const arr=s.docs.map(d=>({id:d.id,...d.data()}));box.innerHTML=(arr.length?arr:def).map(html).join("")}catch(e){box.innerHTML=def.map(html).join("")}}
load("fields","field-list",f=>`<article><h3>${f.title||""}</h3><p>${f.body||""}</p></article>`,defaults.fields);
load("products","product-list",p=>`<article>${p.image?`<img class="img" src="${p.image}">`:""}<span class="badge">${p.stock||"주문 가능"}</span><h3>${p.name||""}</h3><p>${p.desc||""}</p><strong class="price">${p.price||"문의"}</strong><button class="btn" onclick='openBuyModal(${JSON.stringify(p).replaceAll("'","&#39;")})'>구매하기</button></article>`,defaults.products);
load("posts","board-list",p=>`<article>${p.image?`<img class="img" src="${p.image}">`:""}<span class="badge">게시글</span><h3>${p.title||""}</h3><p>${p.body||""}</p></article>`,[]);
load("notices","notice-list",n=>`<article><span class="badge">${n.tag||"공지"}</span><h3>${n.title||""}</h3><p>${n.body||""}</p></article>`,defaults.notices);
async function loadReviews(){const box=document.getElementById("review-list");try{const s=await getDocs(query(collection(db,"reviews"),where("approved","==",true),orderBy("createdAt","desc")));const arr=s.docs.map(d=>d.data());box.innerHTML=(arr.length?arr:defaults.reviews).map(r=>`<article><div class="price">${r.stars||"★★★★★"}</div><p>“${r.body||""}”</p><span>${r.name||"익명"} · ${r.category||""}</span></article>`).join("")}catch(e){box.innerHTML=""}}loadReviews();
window.openBuyModal=(p)=>{selectedProduct=p;buySummary.textContent=`상품명: ${p.name||""}\n가격: ${p.price||"문의"}\n재고: ${p.stock||"주문 가능"}`;document.getElementById("buy-modal").style.display="flex"};window.closeBuyModal=()=>document.getElementById("buy-modal").style.display="none";
function orderText(){return `[천명신당 상품 구매 신청]\n상품명: ${selectedProduct?.name||""}\n가격: ${selectedProduct?.price||""}\n수량: ${buyerQty.value||1}\n이름: ${buyerName.value}\n연락처: ${buyerPhone.value}\n주소: ${buyerAddress.value}\n요청사항: ${buyerMemo.value}`;}
window.copyOrderText=async()=>{await navigator.clipboard.writeText(orderText());alert("주문 내용이 복사되었습니다. 카카오톡에 붙여넣어 보내주세요.")};
window.submitOrder=async()=>{if(!selectedProduct||!buyerName.value||!buyerPhone.value)return alert("이름과 연락처를 입력해 주세요.");await addDoc(collection(db,"orders"),{productId:selectedProduct.id||"",productName:selectedProduct.name||"",price:selectedProduct.price||"",qty:buyerQty.value||1,name:buyerName.value,phone:buyerPhone.value,address:buyerAddress.value,memo:buyerMemo.value,status:"신규",createdAt:serverTimestamp()});alert("구매 신청이 접수되었습니다. 카카오톡으로 결제 안내를 받으세요.");closeBuyModal()};
window.submitReservation=async()=>{if(!resName.value||!resPhone.value||!resBody.value)return alert("이름, 연락처, 내용을 입력해 주세요.");await addDoc(collection(db,"reservations"),{name:resName.value,phone:resPhone.value,field:resField.value,date:resDate.value,body:resBody.value,status:"대기",createdAt:serverTimestamp()});alert("예약 요청이 접수되었습니다.");resName.value=resPhone.value=resDate.value=resBody.value=""};
window.openReviewModal=()=>document.getElementById("review-modal").style.display="flex";window.closeReviewModal=()=>document.getElementById("review-modal").style.display="none";window.submitReview=async()=>{if(!reviewName.value||!reviewBody.value)return alert("내용을 입력해 주세요.");await addDoc(collection(db,"reviews"),{name:reviewName.value,category:reviewCategory.value,stars:reviewStars.value,body:reviewBody.value,approved:false,createdAt:serverTimestamp()});alert("후기 등록 요청 완료");closeReviewModal()};
