import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getFirestore, collection, addDoc, getDocs, query, orderBy, where, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig); const db=getFirestore(app);
const defFields=[{title:"연애 · 재회",body:"상대방 속마음, 연락운, 재회 흐름, 관계 회복 가능성을 살펴봅니다."},{title:"금전운 · 사업운",body:"막힌 흐름, 매출, 계약, 이동, 선택의 방향을 함께 봅니다."},{title:"직장 · 취업운",body:"취업, 이직, 시험, 승진, 직장 내 인간관계 흐름을 살펴봅니다."},{title:"인간관계",body:"가족, 지인, 직장, 주변 사람들과의 갈등과 흐름을 정리합니다."}];
const defProducts=[{name:"한 질문 상담",price:"문의",desc:"하나의 핵심 질문에 대해 현재 흐름과 방향을 살펴드립니다."},{name:"세 질문 상담",price:"문의",desc:"연결된 고민 세 가지를 묶어 흐름을 정리합니다."},{name:"신점 상담",price:"문의",desc:"전반적인 상황과 앞으로의 방향성을 깊이 있게 살펴봅니다."}];
const defNotices=[{tag:"필독",title:"상담은 카카오톡 문의 후 예약제로 진행됩니다.",body:"생년월일, 성별, 본관·성씨, 현재 상황과 질문을 정리해 주시면 상담이 더 원활합니다."}];
const defReviews=[{name:"김OO님",category:"재회 상담",stars:"★★★★★",body:"혼자 마음이 너무 복잡했는데 현재 흐름을 정리하는 데 큰 도움이 되었습니다."}];
function dt(ts){try{return ts&&ts.toDate?ts.toDate().toLocaleDateString("ko-KR"):""}catch(e){return ""}}
async function loadFields(){const box=document.getElementById("field-list");try{const snap=await getDocs(query(collection(db,"fields"),orderBy("createdAt","desc")));const arr=snap.docs.map(d=>d.data());const list=arr.length?arr:defFields;box.innerHTML=list.map(f=>`<article><h3>${f.title||""}</h3><p>${f.body||""}</p></article>`).join("")}catch(e){box.innerHTML=defFields.map(f=>`<article><h3>${f.title}</h3><p>${f.body}</p></article>`).join("")}}
async function loadProducts(){const box=document.getElementById("product-list");try{const snap=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc")));const arr=snap.docs.map(d=>d.data());const list=arr.length?arr:defProducts;box.innerHTML=list.map(p=>`<article>${p.image?`<img class="product-img" src="${p.image}" alt="${p.name||""}">`:""}<span class="badge">상담 서비스</span><h3>${p.name||""}</h3><p>${p.desc||""}</p><strong class="product-price">${p.price||"문의"}</strong><a class="btn primary" href="#reservation">예약하기</a></article>`).join("")}catch(e){box.innerHTML=defProducts.map(p=>`<article><span class="badge">상담 서비스</span><h3>${p.name}</h3><p>${p.desc}</p><strong class="product-price">${p.price}</strong></article>`).join("")}}
async function loadNotices(){const box=document.getElementById("notice-list");try{const snap=await getDocs(query(collection(db,"notices"),orderBy("createdAt","desc")));const arr=snap.docs.map(d=>d.data());const list=arr.length?arr:defNotices;box.innerHTML=list.map(n=>`<article><span>${n.tag||"공지"}</span><h3>${n.title||""}</h3><p>${n.body||""}</p><small>${dt(n.createdAt)}</small></article>`).join("")}catch(e){box.innerHTML=defNotices.map(n=>`<article><span>${n.tag}</span><h3>${n.title}</h3><p>${n.body}</p></article>`).join("")}}
async function loadReviews(){const box=document.getElementById("review-list");try{const snap=await getDocs(query(collection(db,"reviews"),where("approved","==",true),orderBy("createdAt","desc")));const arr=snap.docs.map(d=>d.data());const list=arr.length?arr:defReviews;box.innerHTML=list.map(r=>`<article><div class="stars">${r.stars||"★★★★★"}</div><p>“${r.body||""}”</p><span>${r.name||"익명"} · ${r.category||"상담 후기"}</span></article>`).join("")}catch(e){box.innerHTML=defReviews.map(r=>`<article><div class="stars">${r.stars}</div><p>“${r.body}”</p><span>${r.name} · ${r.category}</span></article>`).join("")}}
window.submitReservation=async()=>{const name=resName.value.trim(),phone=resPhone.value.trim(),field=resField.value,date=resDate.value.trim(),body=resBody.value.trim(); if(!name||!phone||!body)return alert("이름, 연락처, 상담 내용을 입력해 주세요."); try{await addDoc(collection(db,"reservations"),{name,phone,field,date,body,status:"대기",createdAt:serverTimestamp()});alert("예약 요청이 접수되었습니다. 카카오톡으로 확인 연락을 드립니다.");resName.value="";resPhone.value="";resDate.value="";resBody.value=""}catch(e){alert("예약 접수 중 오류가 발생했습니다.")}};
window.openReviewModal=()=>{document.getElementById("document.getElementById('review-modal')").style.display="flex"}; window.closeReviewModal=()=>{document.getElementById("document.getElementById('review-modal')").style.display="none"};
window.submitReview=async()=>{const name=reviewName.value.trim(),category=reviewCategory.value.trim(),stars=reviewStars.value,body=reviewBody.value.trim(); if(!name||!category||!body)return alert("이름, 상담 분야, 후기 내용을 모두 입력해 주세요."); try{await addDoc(collection(db,"reviews"),{name,category,stars,body,approved:false,createdAt:serverTimestamp()});alert("후기가 등록 요청되었습니다. 관리자 승인 후 공개됩니다.");reviewName.value="";reviewCategory.value="";reviewBody.value="";closeReviewModal()}catch(e){alert("등록 중 오류가 발생했습니다.")}};
loadFields();loadProducts();loadNotices();loadReviews();
